/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as PestsPhotoSearchRouteImport } from './routes/pests.photo-search'
import { Route as FarmsNewRouteImport } from './routes/farms.new'
import { Route as AdminRentalsRouteImport } from './routes/admin.rentals'
import { Route as FarmsFarmIdRiskRouteImport } from './routes/farms.$farmId.risk'
import { Route as FarmsFarmIdMachinesRouteImport } from './routes/farms.$farmId.machines'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const PestsPhotoSearchRoute = PestsPhotoSearchRouteImport.update({
  id: '/pests/photo-search',
  path: '/pests/photo-search',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsNewRoute = FarmsNewRouteImport.update({
  id: '/farms/new',
  path: '/farms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRentalsRoute = AdminRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AdminRoute,
} as any)
const FarmsFarmIdRiskRoute = FarmsFarmIdRiskRouteImport.update({
  id: '/farms/$farmId/risk',
  path: '/farms/$farmId/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmsFarmIdMachinesRoute = FarmsFarmIdMachinesRouteImport.update({
  id: '/farms/$farmId/machines',
  path: '/farms/$farmId/machines',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/farmer': typeof FarmerRoute
  '/login': typeof LoginRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/farms/new': typeof FarmsNewRoute
  '/pests/photo-search': typeof PestsPhotoSearchRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/farms/$farmId/machines': typeof FarmsFarmIdMachinesRoute
  '/farms/$farmId/risk': typeof FarmsFarmIdRiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/farmer': typeof FarmerRoute
  '/login': typeof LoginRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/farms/new': typeof FarmsNewRoute
  '/pests/photo-search': typeof PestsPhotoSearchRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/farms/$farmId/machines': typeof FarmsFarmIdMachinesRoute
  '/farms/$farmId/risk': typeof FarmsFarmIdRiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/farmer': typeof FarmerRoute
  '/login': typeof LoginRoute
  '/admin/rentals': typeof AdminRentalsRoute
  '/farms/new': typeof FarmsNewRoute
  '/pests/photo-search': typeof PestsPhotoSearchRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/farms/$farmId/machines': typeof FarmsFarmIdMachinesRoute
  '/farms/$farmId/risk': typeof FarmsFarmIdRiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/farmer'
    | '/login'
    | '/admin/rentals'
    | '/farms/new'
    | '/pests/photo-search'
    | '/reports/$reportId'
    | '/farms/$farmId/machines'
    | '/farms/$farmId/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/farmer'
    | '/login'
    | '/admin/rentals'
    | '/farms/new'
    | '/pests/photo-search'
    | '/reports/$reportId'
    | '/farms/$farmId/machines'
    | '/farms/$farmId/risk'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/farmer'
    | '/login'
    | '/admin/rentals'
    | '/farms/new'
    | '/pests/photo-search'
    | '/reports/$reportId'
    | '/farms/$farmId/machines'
    | '/farms/$farmId/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  FarmerRoute: typeof FarmerRoute
  LoginRoute: typeof LoginRoute
  FarmsNewRoute: typeof FarmsNewRoute
  PestsPhotoSearchRoute: typeof PestsPhotoSearchRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  FarmsFarmIdMachinesRoute: typeof FarmsFarmIdMachinesRoute
  FarmsFarmIdRiskRoute: typeof FarmsFarmIdRiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pests/photo-search': {
      id: '/pests/photo-search'
      path: '/pests/photo-search'
      fullPath: '/pests/photo-search'
      preLoaderRoute: typeof PestsPhotoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/new': {
      id: '/farms/new'
      path: '/farms/new'
      fullPath: '/farms/new'
      preLoaderRoute: typeof FarmsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rentals': {
      id: '/admin/rentals'
      path: '/rentals'
      fullPath: '/admin/rentals'
      preLoaderRoute: typeof AdminRentalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/farms/$farmId/risk': {
      id: '/farms/$farmId/risk'
      path: '/farms/$farmId/risk'
      fullPath: '/farms/$farmId/risk'
      preLoaderRoute: typeof FarmsFarmIdRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farms/$farmId/machines': {
      id: '/farms/$farmId/machines'
      path: '/farms/$farmId/machines'
      fullPath: '/farms/$farmId/machines'
      preLoaderRoute: typeof FarmsFarmIdMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminRentalsRoute: typeof AdminRentalsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRentalsRoute: AdminRentalsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  FarmerRoute: FarmerRoute,
  LoginRoute: LoginRoute,
  FarmsNewRoute: FarmsNewRoute,
  PestsPhotoSearchRoute: PestsPhotoSearchRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  FarmsFarmIdMachinesRoute: FarmsFarmIdMachinesRoute,
  FarmsFarmIdRiskRoute: FarmsFarmIdRiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
